name: Python Checks
description: Run Python Linting and Type Checking
runs:
  using: "composite"
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5

    - name: Run ruff
      run: uv run ruff check
      shell: bash

    - name: Run mypy
      run: uv run mypy zeroq tests
      shell: bash
