name: Publish Release
description: Publish the package to PyPI
runs:
  using: "composite"
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: "wheels-*/*"

    - name: Publish to PyPI
      uses: PyO3/maturin-action@v1
      env:
        MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      with:
        command: upload
        args: --non-interactive --skip-existing wheels-*/*
