name: Build Wheels
description: Build Python wheels
inputs:
  target:
    required: true
  artifact_prefix:
    required: true
  manylinux:
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Python (Windows)
      if: ${{ matrix.os == 'windows' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: ${{ matrix.architecture }}

    - name: Set up Python (Non-Windows)
      if: ${{ matrix.os != 'windows' }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ inputs.target }}
        args: --release --out dist --find-interpreter
        sccache: "true"
        manylinux: ${{ inputs.manylinux }}

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_prefix }}-${{ inputs.target }}
        path: dist
