name: Rust Checks
description: Run Rust Formatting, Linting, and Compilation Checks
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Show Rust version
      run: rustc --version && cargo --version
      shell: bash

    - name: Run cargo fmt
      run: cargo fmt --check
      shell: bash

    - name: Run cargo clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
      shell: bash

    - name: Run cargo check
      run: cargo check --all-targets --all-features
      shell: bash
