name: Benchmark and Plot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run benchmarks on'
        required: true
        default: 'main'
        type: string

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5

    - name: Run benchmarks
      run: |
        uv run pytest tests/benchmarks/ \
          --benchmark-only \
          --benchmark-autosave \
          --timeout=0 \
          --benchmark-disable-gc \
          --benchmark-json=benchmark.json

    - name: Generate CSV report
      run: |
        uv run py.test-benchmark compare benchmark.json --csv=benchmark_results.csv

    - name: Generate plot
      run: |
        uv run python tests/benchmarks/build_plot.py benchmark_results.csv -o benchmark_plot.png

    - name: Update README
      run: |
        cp benchmark_plot.png ./tests/benchmarks/benchmark_plot.png

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add benchmark_plot.png
        git commit -m "Update README with latest benchmark results [skip ci]"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          benchmark_plot.png
          benchmark_results.csv
