name: Build Wheels & sdist

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    needs: [tests]
    strategy:
      matrix:
        include:
          # Linux (manylinux = auto)
          - os: linux
            runner: ubuntu-22.04
            target: x86_64
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: x86
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: aarch64
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: armv7
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: s390x
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: ppc64le
            manylinux: auto
            artifact_prefix: wheels-linux
          # Musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: x86_64
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: x86
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: aarch64
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: armv7
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          # Windows
          - os: windows
            runner: windows-latest
            target: x64
            manylinux: ''
            artifact_prefix: wheels-windows
            architecture: x64
          - os: windows
            runner: windows-latest
            target: x86
            manylinux: ''
            artifact_prefix: wheels-windows
            architecture: x86
          # macOS
          - os: macos
            runner: macos-13
            target: x86_64
            manylinux: ''
            artifact_prefix: wheels-macos
          - os: macos
            runner: macos-14
            target: aarch64
            manylinux: ''
            artifact_prefix: wheels-macos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_prefix }}-${{ matrix.target }}
          path: dist

  sdist:
    name: Build Source Distribution (sdist)
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist
