name: Rust Checks

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  rust-checks:
    name: Rust Formatting, Linting, and Compilation Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Show Rust version
        run: rustc --version && cargo --version
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run cargo check
        run: cargo check --all-targets --all-features
