name: Tests (Cross-Platform)

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Test on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    needs: [rust-checks, python-checks]
    strategy:
      matrix:
        include:
          # Linux (manylinux = auto)
          - os: linux
            runner: ubuntu-22.04
            target: x86_64
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: x86
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: aarch64
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: armv7
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: s390x
            manylinux: auto
            artifact_prefix: wheels-linux
          - os: linux
            runner: ubuntu-22.04
            target: ppc64le
            manylinux: auto
            artifact_prefix: wheels-linux
          # Musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: x86_64
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: x86
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: aarch64
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          - os: musllinux
            runner: ubuntu-22.04
            target: armv7
            manylinux: musllinux_1_2
            artifact_prefix: wheels-musllinux
          # Windows
          - os: windows
            runner: windows-latest
            target: x64
            manylinux: ''
            artifact_prefix: wheels-windows
            architecture: x64
          - os: windows
            runner: windows-latest
            target: x86
            manylinux: ''
            artifact_prefix: wheels-windows
            architecture: x86
          # macOS
          - os: macos
            runner: macos-13
            target: x86_64
            manylinux: ''
            artifact_prefix: wheels-macos
          - os: macos
            runner: macos-14
            target: aarch64
            manylinux: ''
            artifact_prefix: wheels-macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11
      - name: Run tests
        run: uv run pytest
